# Data Preprocessing

This notebook prepares the Recruitment dataset for neural network modeling by selecting features, encoding categorical variables, splitting the dataset, and scaling numerical features while avoiding data leakage.

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.compose import ColumnTransformer

In [2]:
data_path = Path("../data/Datasets.xlsx")

df = pd.read_excel(
    data_path,
    sheet_name="Recruitment"
)

df.head()

  Candidate_ID Position  Experience  Tech_Score  Interview    Status
0        C0001       DS           4          78         83     Hired
1        C0002       DS           6          99         63     Hired
2        C0003       SE           7          78         69  Rejected
3        C0004       SE           1          89         42  Rejected
4        C0005       QA           4          77         48   Pending

In [3]:
X = df.drop(columns=["Candidate_ID", "Status"])
y = df["Status"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (200, 4)
Target shape: (200,)

In [4]:
X.head()

  Position  Experience  Tech_Score  Interview
0       DS           4          78         83
1       DS           6          99         63
2       SE           7          78         69
3       SE           1          89         42
4       QA           4          77         48

In [5]:
y.head()

0       Hired
1       Hired
2    Rejected
3    Rejected
4     Pending
Name: Status, dtype: str

In [6]:
label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Classes:", label_encoder.classes_)
print("Encoded target sample:", y_encoded[:10])

Classes: ['Hired' 'Pending' 'Rejected']
Encoded target sample: [0 0 2 2 1 0 0 0 1 1]

In [7]:
for index, class_name in enumerate(label_encoder.classes_):
    print(f"{class_name} -> {index}")

Hired -> 0
Pending -> 1
Rejected -> 2

In [8]:
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y_encoded,
    test_size=0.30,
    random_state=42,
    stratify=y_encoded
)